### ISSUE TITLE
Keyword Checklist: Unity Package

### ISSUE THREAD

**Issue by EloiStree** [EloiStree/HelloGitForUnity3D#46]
**Basic**:
- [x] Create a Git repository.
- [x] Create a Unity3D quarantine project.
- [x] Create a folder named "P" in the `Assets` directory.
- [x] Clone the Git repository into the "P" folder.  
  - [x] Avoid having a Git repository inside another Git repository.
- [x] Create a `package.json` file in the "P" folder.
- [ ] Create a `Runtime` folder.
- [ ] In the `Runtime` folder, create an assembly named "be.company.toolboxname.Runtime".
  - [ ] Keep it alphanumerical.
  - [ ] Keep it short (if possible).
  - [ ] See [Unity3D Manual](https://docs.unity3d.com/Manual/upm-manifestPkg.html#:~:text=Unity%20uses%20a%20package%20manifest,registered%20name%20and%20version%20number).
- [x] Create base folders: 3D, 2D, Prefab, Scene, Material, etc.
- [ ] Add a photo in the `README.md` (if possible).
- [ ] Add a sample entry in the `package.json`.
- [ ] Add the repository URL in the Unity project to check if everything is correctly set up.
- [ ] Ensure you have demonstrative prefabs.
- [ ] Ensure you have a scene that demonstrates how to use your tool.
- [ ] Add some text documentation in the scene.
- [ ] If you have time, clean up the assets and add some information in `README.md`.
- [ ] Copy the manifest id to readme.md
  - [ ] Add repository in a project
  - [ ] Go fetch the "be.elab.yourtoolbox":"https://www.github.com...git", near Asset the package/manifest.json
  - [ ] Add it to your package readme.md

**Optional**:
- [ ] Add an `Intent.md` file to remind yourself why you created the package.
  - [ ] Include the 4 pillars (if applicable).
- [ ] Add a `required.md` file to document other packages required.
- [ ] Publish the package on OpenUPM.
- [ ] Add a sample scene.
- [ ] Add a log file.
- [ ] Add a license file.
  - [ ] Create a license file using an online license generator.
- [ ] Verify your author name in `package.json`.
- [ ] Add Unity3D dependencies if you need systems like the Input System, TextMesh Pro, etc.
- [ ] Add some TDD scripts to test your code.

If you create Editor script:
- [ ] Add a folder Editor
- [ ] Create an assembly in it called "be.company.toolname.Editor"
- [ ] Add by name reference to the assembly to target "be.company.toolname.Runtime"
- [ ] Add your editor script in it

# Fork to work in team

## Magic Door 24
Example:
- Google Sheet : https://docs.google.com/spreadsheets/d/1ix5-vepfv-0SybpaODpU39KDhYOog2d64DxLUBR03CU/edit?gid=0#gid=0
- Itch.io : https://eloistree.itch.io/magicdooratelierdegroupetechnocite

Step: 
- [ ] Create a google sheet for the team and share it to the team member
- [ ] Create you need a column with the User Topic of the tool, git hash, git link of the participants 
- [ ] Create a column with your integrator git fork
  - [ ] If any git is problematic, fork it and add your correction instead

**Comment by EloiStree** [comment]
https://choosealicense.com

**Comment by EloiStree** [comment]
A tutorial a bit more complete I write years ago:
https://github.com/EloiStree/HelloUnityPackage/wiki
